### ISSUE TITLE
Doesn't work with Rails?

### ISSUE THREAD

**Issue by nateberkopec** [seattlerb/minitest-bisect#6] opened 2015-05-12 20:56 UTC
```bash
ruby -I"lib:test" test/integration/todo_mvc_test.rb
```
...works just fine.

```bash
be minitest_bisect --seed 51515 test/integration/todo_mvc_test.rb 
reproducing...
Reproduction run passed? Aborting.
```

...exits quickly without running the test.

**Comment by zenspider** [comment] 2015-05-12 21:56
Define "works just fine"? If it passes, then minitest_bisect will do the above and exit.

**Comment by nateberkopec** [comment] 2015-05-12 23:21
```bash
ruby -I"lib:test" test/integration/todo_mvc_test.rb --seed 51515
```

...results in one test failure. Also, I know it's not running the tests because it exits almost immediately after I hit enter, and this suite takes 60 seconds to run.

**Comment by zenspider** [comment] 2015-05-13 00:02
Hrm... ok. then we need to dig in. For starters, run w/ `ruby -d -S minitest_bisect` (or something similar).

**Comment by zenspider** [comment] 2015-05-13 00:32
(and not that it'll affect this bug, but don't forget to run with `--rails` to have extra brains activated.)

**Comment by zenspider** [comment] 2015-05-19 02:19
OK. After a tremendously frustrating yak shave, I've committed fixes to minitest and minitest-server, as well as those enhancements to minitest-bisect we discussed.

This still won't fix the issue you're having, as I can't reproduce it yet, but I think this fixes the NEXT failure you were going to get (and anyone else using rails + web-console). So there's that.

**Comment by zenspider** [comment] 2015-05-22 21:33
Where does this stand?

**Comment by sheldond** [comment] 2015-05-29 20:37
Hey I tried minitest-bisect today on a rails 4.2.1 project (saw it at railsconf, thanks for the talks!), I have a similar issue:

```
$ MTB_VERBOSE=2 bundle exec minitest_bisect --seed 4146 test/integration/project_authentication_test.rb
reproducing...

/Users/sheldon/.rvm/rubies/ruby-2.2.2/bin/ruby  -e 'require "./test/integration/project_authentication_test.rb"' -- --seed 4146 --server 71915

/Users/sheldon/Dev/project-substance-marketplace/test/integration/project_authentication_test.rb:1:in `require': cannot load such file -- test_helper (LoadError)
	from /Users/sheldon/Dev/project-substance-marketplace/test/integration/project_authentication_test.rb:1:in `<top (required)>'
	from -e:1:in `require'
	from -e:1:in `<main>'
Reproduction run passed? Aborting. Try running with MTB_VERBOSE=2 to verify.
```

minitest_bisect works if I add "/Users/sheldon/Dev/project-substance-marketplace/test" to the load path.

Thanks!

**Comment by zenspider** [comment] 2015-05-29 21:02
However you run that single file normally is the way you should run it with bisect. So in both cases, you'd probably need a `-Itest` or your test file needs to manipulate the load path itself.

Try running:

```
% ruby  -Itest ./test/integration/project_authentication_test.rb
```

and once that works, replace ruby with `minitest_bisect`

**Comment by sheldond** [comment] 2015-05-29 22:20
Ah gotcha, that works then! Perhaps this solves @nateberkopec's issue as well?

**Comment by CamJN** [comment] 2015-06-07 07:17
That doesn't fix the issue for me, `ruby  -Itest ./test/integration/project_authentication_test.rb` runs the tests, which exhibit the failure. Then `~/.rbenv/shims/minitest_bisect  -Itest test/controllers/subscriptions_controller_test.rb` just says `Reproduction run passed? Aborting. Try running with MTB_VERBOSE=2 to verify.`

And to @zenspider's point about how one runs the tests normally, in my case that's with `rake test`.


running with `MTB_VERBOSE=2` gives:
```
MTB_VERBOSE=2 ~/.rbenv/shims/minitest_bisect  -Itest test/controllers/subscriptions_controller_test.rb  --seed 58197
reproducing...

/Users/camdennarzt/.rbenv/versions/2.2.2/bin/ruby -Itest -e 'require "./test/controllers/subscriptions_controller_test.rb"' -- --seed 58197 --server 65235

Run options: --seed 58197 --server 65235

# Running:

.........................................................................F/Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:1718:in `current_server': DRb::DRbServerNotFound (DRb::DRbConnError)
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:1787:in `to_id'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:1103:in `initialize'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:650:in `new'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:650:in `make_proxy'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:567:in `rescue in dump'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:564:in `dump'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:611:in `block in send_request'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:610:in `each'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:610:in `send_request'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:925:in `send_request'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:1253:in `send_message'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:1142:in `block (2 levels) in method_missing'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:1229:in `open'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:1141:in `block in method_missing'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:1160:in `with_friend'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:1140:in `method_missing'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-server-1.0.2/lib/minitest/server_plugin.rb:37:in `record'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:633:in `block in record'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:632:in `each'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:632:in `record'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:306:in `run_one_method'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:294:in `block (2 levels) in run'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:293:in `each'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:293:in `block in run'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:332:in `on_signal'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:319:in `with_info_handler'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:292:in `run'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:155:in `block in __run'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:155:in `map'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:155:in `__run'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:129:in `run'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:56:in `block in autorun'
Reproduction run passed? Aborting. Try running with MTB_VERBOSE=2 to verify.
```

**Comment by CamJN** [comment] 2015-06-07 20:30
`ruby -Itest -d -S minitest_bisect test/controllers/subscriptions_controller_test.rb` 
gives: 
```
Exception `LoadError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems.rb:1222 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems.rb:1231 - cannot load such file -- rubygems/defaults/ruby
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `DRb::DRbBadScheme' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:825 - drbunix:/var/folders/0x/gvllnpys5p9cngslb8r5pnq80000gn/T/minitest.77932
Exception `DRb::DRbBadScheme' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:825 - drbunix:/var/folders/0x/gvllnpys5p9cngslb8r5pnq80000gn/T/minitest.77932
reproducing...
Reproduction run passed? Aborting. Try running with MTB_VERBOSE=2 to verify.
```

**Comment by zenspider** [comment] 2015-06-08 22:06
```
/Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:1718:in `current_server': DRb::DRbServerNotFound (DRb::DRbConnError)
```

says that it can't connect back to the drb server that debride is using to control sub-test runs. I suspect this is a separate issue. Can you file a separate issue?

**Comment by zenspider** [comment] 2015-06-09 07:01
Deleting tangental comments now that #6 has been filed...

**Comment by zenspider** [comment] 2015-07-25 21:59
OI! @nateberkopec! You ever gonna find time to hunt this down with me?

**Comment by zenspider** [comment] 2015-08-14 21:11
I'm guessing the answer is "no" then... Closing.

**Closed by zenspider** 2015-08-14 21:11 UTC
